run: { scenario: EXP_HE_llm_small, seed: 25, steps: 20, population: 80, results_dir: "results", log_every: 1, agent: llm }
income: { theta: 5.0, beta: 1, eps_std: 1.0, pln: { m: 10.0, alpha: 2.5, sigma: 0.6 } }
goods:  { p: 2.0, xi: 0.6 }
preferences: { gamma_mean: 1.0, gamma_std: 0.1, tau_min: 0.0, tau_max: 1.0 }
tax: { on: false }
network: { dynamic: true, type: "erdos_renyi", erdos_renyi: { p_edge: 0.02 },
           dynamics: { reevaluate_every: 3, add_prob: 0.08, drop_prob: 0.02, max_degree: 40 } }
logging: { write_csv: true, write_parquet: false, snapshot_config: true }