run: { scenario: EXP_HFR_llm_small, seed: 23, steps: 20, population: 80, results_dir: "results", log_every: 1, agent: llm }
income: { theta: 5.0, beta: 1, eps_std: 1.0, pln: { m: 10.0, alpha: 2.5, sigma: 0.6 } }
goods:  { p: 2.0, xi: 0.6 }
preferences: { gamma_mean: 1.0, gamma_std: 0.1, tau_min: 0.0, tau_max: 1.0 }
tax: { on: true, a: 0.0997, b: 0.003 }
network: { dynamic: false, type: "erdos_renyi", erdos_renyi: { p_edge: 0.05 },
           dynamics: { reevaluate_every: 1, add_prob: 0.0, drop_prob: 0.0, max_degree: 80 } }
logging: { write_csv: true, write_parquet: false, snapshot_config: true }